# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Get_To_Know_SapceX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'UIScrollView-InfiniteScroll', '~> 1.3.0'
  pod 'SDWebImage'

  target 'Get_To_Know_SapceXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Get_To_Know_SapceXUITests' do
    # Pods for testing
  end

end
